name: ORSO Val. NIST Web Calculator

on:
  push:
    branches: [ master ]
  pull_request:
  schedule:
    - cron:  '0 0 * * 1'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  validate_nistweb:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.13'
      - name: setup apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends build-essential

      - name: Install Python packages
        run: |
          python3 -m venv validate
          source validate/bin/activate

          python3 -m pip install --upgrade pip
          python3 -m pip install wheel setuptools
          python3 -m pip install numpy scipy cython pytest requests

      - name: Validate
        run: |
          source validate/bin/activate
          # run validation via pytest (for Python packages)
          pytest validation/scripts/test_nistweb.py
